config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  resources :climbers do
    resources :ticks
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climber.rb
class Climber < ApplicationRecord
  has_many :ticks, dependent: :destroy
  validates :name, presence: true
end

app/models/tick.rb
class Tick < ApplicationRecord
  belongs_to :climber
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/climbers_controller.rb
class ClimbersController < ApplicationController
  def index
    @climbers = Climber.all
  end

  def show
    @climber = Climber.find(params[:id])
  end

  def new
    @climber = Climber.new
  end

  def edit
    @climber = Climber.find(params[:id])
  end

  def update
    @climber = Climber.find(params[:id])

    if @climber.update(climber_params)
      redirect_to @climber
    else
      render 'edit'
    end
  end

  def create
    @climber = Climber.new(climber_params)

    if @climber.save()
      redirect_to @climber
    else
      render 'new'
    end
  end

  def destroy
    @climber = Climber.find(params[:id])
    @climber.destroy

    redirect_to climbers_path
  end

  private
    def climber_params
      params.require(:climber).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ticks_controller.rb
class TicksController < ApplicationController
  def destroy
    @climber = Climber.find(params[:climber_id])
    @tick = @climber.ticks.find(params[:id])
    @tick.destroy
    redirect_to climber_path(@climber)
  end

  def create
    @climber = Climber.find(params[:climber_id])
    @tick = @climber.ticks.create(tick_params)
    redirect_to climber_path(@climber)
  end

  private
    def tick_params
      params.require(:tick).permit(:name, :send_date, :grade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climbers_helper.rb
module ClimbersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/views/climbers/_form.erb
<%= form_with model: @climber, local: true do |form| %>
  <% if @climber.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@climber.errors.count, "error") %> Prohibited This Climber From Being Saved:
      </h4>
      <ul>
        <% @climber.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%=  form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <%= form.submit %>
<% end %>

app/views/climbers/_tick_list.erb
<% if @climber.ticks.any? %>
  <h6>Tick List:</h6>
  <ul>
    <%= render @climber.ticks %>
  </ul>
<% end %>

app/views/climbers/edit.erb
<h6>Edit Climber <%= @climber.name %></h6>
<%= render 'form' %>
<%= link_to 'back', climbers_path %>

app/views/climbers/index.erb
<h5>Climbers</h5>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  <% @climbers.each do |climber| %>
    <tr>
      <td><%= climber.name %></td>
      <td><%= link_to 'Show', climber_path(climber) %></td>
      <td><%= link_to 'Edit', edit_climber_path(climber) %></td>
      <td><%= link_to 'Destroy', climber_path(climber),
                      method: :delete,
                      data: {confirm: "Are you sure?"}
      %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add Climber', new_climber_path %>

app/views/climbers/new.erb
<h5>New Climber</h5>
<%= render 'form' %>
<%= link_to 'Back', climbers_path %>

app/views/climbers/show.erb
<h4>Climber Detail</h4>
<p>
  <strong>Name: </strong>
  <%= @climber.name %>
</p>
<%= render 'tick_list' %>
<%= render 'ticks/form' %>

<%= link_to 'Add Another Climber', new_climber_path %>
<%= link_to 'Edit', edit_climber_path(@climber) %>
<%= link_to 'View Climbers', climbers_path %>

app/views/home/index.html.erb
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoonComp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="has-background-white-ter">
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <%= image_tag("brand-logo.png", width: 112, height: 100) %>
        </a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarLinks">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="navbarLinks">
        <div class="navbar-end">
          <% if user_signed_in? %>
            <div class="navbar-item">
              Logged in as &nbsp;<strong class="has-text-white"><%= current_user.email %></strong>.
            </div>
            <div class="navbar-item has-dropdown is-hoverable is-left">
              <a class="navbar-link">
                <i class="fa fa-cog"></i>
              </a>
              <div class="navbar-dropdown is-right">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item'  %>
                <hr class="navbar-divider">
                <a class="navbar-item">
                  Report an issue
                </a>
              </div>
            </div>
          <% else %>
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="buttons">
                  <%= link_to 'Sign Up', new_user_registration_path, :class => 'button is-white' %>
                  <%= link_to 'Login', new_user_session_path, :class => 'button is-white' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <% if notice %>
          <div class="notification is-info"><%= notice %></div>
        <% end %>
        <% if alert %>
          <div class="notification is-danger">
            <%= alert %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/ticks/_form.erb
<%= form_with(model: [@climber, @climber.ticks.build ],
              local: true) do |form| %>
  <h6>Add A Tick:</h6>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.label :send_date %>
    <%= form.date_field :send_date %>
    <br>
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </p>
  <%= form.submit %>
<% end %>

app/views/ticks/_tick.erb
<li>
  <strong><%= tick.name %></strong><br>
  Date: <%= tick.send_date %> <br>
  Grade: <%= tick.grade %> <br>
  <%= link_to 'Delete Tick', [tick.climber, tick],
              method: :delete,
              data: {confirm: "Are you sure?"}
  %>
</li>